name: Compile

on: 
  push:
    branches: [ workflow ]
  pull_request:
      branches: [ workflow ]

jobs:
    build:
        
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: sudo ./setup.sh
      - run: make
