name: Compile

on: 
  push:
    branches: [ workflow ]
  pull_request:
      branches: [ workflow ]

jobs:
    build:
        
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - run: sudo ./Code/setup.sh
      - run: make
