name: Compile

on: 
  push:
    branches: [ workflow ]
  pull_request:
      branches: [ workflow ]

jobs:
    build:
        
      runs-on: ubuntu-latest
      
      steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          #- run: make
