name: Compile

on: 
  push:
    branches: [ workflow ]
  pull_request:
      branches: [ workflow ]

jobs:
    build:
        
      runs-on: ubuntu-latest
      
      steps:
      - run: |
          echo $PWD
          cd Code
          make
