name: Compile

on: 
  push:
      branches: [ add_protobuf ]
  pull_request:
      branches: [ main ]

jobs:
    build:
      defaults:
          run: 
            working-directory: ./Code
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - run: sudo ./setup.sh
      - run: ./build.sh
